name: Build Mac Binaries

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Important for JUCE submodule

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install CMake
      run: brew install cmake

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF

    - name: Build plugins
      run: |
        cd build
        cmake --build . --config Release --parallel

    - name: Verify builds exist
      run: |
        echo "Checking for VST3..."
        ls -la build/ReallyCheap-Twenty_artefacts/Release/VST3/ || echo "VST3 not found"
        echo "Checking for AU..."
        ls -la build/ReallyCheap-Twenty_artefacts/Release/AU/ || echo "AU not found"

    - name: Package Mac plugins
      run: |
        mkdir mac-plugins
        
        # Copy VST3 if it exists
        if [ -d "build/ReallyCheap-Twenty_artefacts/Release/VST3/ReallyCheap-Twenty.vst3" ]; then
          cp -R "build/ReallyCheap-Twenty_artefacts/Release/VST3/ReallyCheap-Twenty.vst3" mac-plugins/
          echo "✅ VST3 packaged"
        else
          echo "❌ VST3 not found"
        fi
        
        # Copy AU if it exists
        if [ -d "build/ReallyCheap-Twenty_artefacts/Release/AU/ReallyCheap-Twenty.component" ]; then
          cp -R "build/ReallyCheap-Twenty_artefacts/Release/AU/ReallyCheap-Twenty.component" mac-plugins/
          echo "✅ AU packaged"
        else
          echo "❌ AU not found"
        fi
        
        # List what we packaged
        echo "Packaged plugins:"
        ls -la mac-plugins/

    - name: Upload Mac plugins as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ReallyCheap-Twenty-Mac-Plugins
        path: mac-plugins/
        retention-days: 30

    - name: Create release info
      run: |
        echo "ReallyCheap Twenty Mac Build" > build-info.txt
        echo "Built on: $(date)" >> build-info.txt
        echo "Commit: ${{ github.sha }}" >> build-info.txt
        echo "Runner: ${{ runner.os }}" >> build-info.txt
        echo "" >> build-info.txt
        echo "Contents:" >> build-info.txt
        ls -la mac-plugins/ >> build-info.txt

    - name: Upload build info
      uses: actions/upload-artifact@v4
      with:
        name: Build-Info
        path: build-info.txt
        retention-days: 30